export default {
    en: {
        home: 'Home',
        about: 'About',
        delivery: 'Delivery',
        help: 'Help',
        cabinet: 'kabinet',
        productsearch: 'Product search',
        searchingresults: 'searching results',
        categories: 'categories',
        basket: 'basket',
        phone: 'Phone',
        socialnetworks: 'SOCIAL NETWORKS',
        email: 'email',
        myorders: 'My orders',
        myprofile: 'My profile',
        addcart: 'Add to cart',
        fio: 'ФИО',
        address: 'address',
        formpayment: 'Form of payment',
        region: 'Region',
        cashterminal: 'Cash or terminal',
        checkout: 'Checkout',
        productsorder: 'Products in order',
        numberresults: 'Number of Results',
        vegetables: 'Vegetables',
        fruits: 'Fruits',
        driedfruits: 'Dried fruits',
        nuts: 'Nuts',
        price: 'Price',
        sections: 'Разделы',
        new: 'New',
        topsales: 'Top sales',
        discounts:'Discounts',
        ordernumber: 'Buyurtma raqami',
        date:'date',
        status:'Status',
        customeraddress: 'Customer Address',
        paymentmethod: 'Payment method',
        amount: 'Amount'
    },
    ru: {
        home: 'Главная',
        about: 'О нас',
        delivery: 'Доставка',
        help: 'Помощь',
        cabinet: 'кабинет',
        productsearch: 'Поиск товаров',
        searchingresults: 'Результаты поиска',
        categories: 'категории',
        basket: 'корзина',
        phone: 'Телефон',
        socialnetworks: 'СОЦИАЛЬНЫЕ СЕТИ',
        email: 'email',
        myorders: 'Мои заказы',
        myprofile: 'Мой профиль',
        addcart: 'в корзину',
        fio: 'ФИО',
        address: 'Адрес',
        formpayment: 'Форма оплаты',
        region: 'Регион',
        cashterminal: 'Наличные или терминал',
        checkout: 'Оформить заказ',
        productsorder: 'Товары в заказе',
        numberresults: 'Количество результатов',
        vegetables: 'Овощи',
        fruits: 'Фрукты',
        driedfruits: 'Сухофрукты',
        nuts: 'Орехи',
        price: 'Цена',
        sections: 'Разделы',
        new: 'Новые',
        topsales: 'Топ продаж',
        discounts: 'Скидки',
        ordernumber: 'Номер заказа',
        date: 'Дата',
        status: 'Статус',
        customeraddress: 'Адрес клиента',
        paymentmethod: 'Метод оплаты',
        amount: 'Сумма'
    },
    uz: {
        home:'Bosh sahifa',
        about: 'Biz haqimizda',
        delivery: 'Yetkazib berish',
        help: 'Yordam',
        cabinet: 'cabinet',
        productsearch: 'Mahsulotni qidirish',
        searchingresults: 'qidiruv natijalari',
        categories: 'kategoryalar',
        basket: 'savatcha',
        phone: 'Telefon',
        socialnetworks: 'IJTIMOIY TARMOQLAR',
        email: 'email',
        myorders: 'Mening buyurtmalarim',
        myprofile: 'Mening profilim',
        addcart: 'savatga qo‘shish',
        fio: 'FIO',
        address: 'Manzil',
        formpayment: 'To\'lov shakli',
        region: 'Viloyat',
        cashterminal: 'Naqd pul yoki terminal',
        checkout: 'Tekshirib ko\'rmoq',
        productsorder: 'Buyurtma bo\'yicha mahsulotlar',
        numberresults: 'Natijalar soni',
        vegetables: 'Sabzavotlar',
        fruits: 'Mevalar',
        driedfruits: 'Quritilgan mevalar',
        nuts: 'Yong\'oqlar',
        price: 'Narxi',
        sections: 'Bo\'limlar',
        new: 'Yangi',
        topsales: 'sotuvlar',
        discounts: 'Chegirmalar',
        ordernumber: 'Buyurtma raqami',
        date: 'sana',
        status: 'Holat',
        customeraddress: 'Xaridor manzili',
        paymentmethod: 'To\'lov uslubi',
        amount: 'Miqdor'
    }
}




